services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DstBug!2025"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "DstBug!2025" -Q "SELECT 1" -No
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    environment:
      TZ: Europe/Warsaw
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: "DstBug!2025"
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
